<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:x="http://www.w3.org/2001/XMLSchema"
 xmlns:t="urn:soap-envelope-test" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:s12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="urn:soap-envelope-test">
 <w:types><x:schema targetNamespace="urn:soap-envelope-test"><x:element name="value" type="x:string"/></x:schema></w:types>
 <w:message name="Value"><w:part name="body" element="t:value"/></w:message>
 <w:portType name="P"><w:operation name="echo"><w:input message="t:Value"/><w:output message="t:Value"/></w:operation></w:portType>
 <w:binding name="B11" type="t:P"><s:binding transport="http://schemas.xmlsoap.org/soap/http"/>
  <w:operation name="echo"><s:operation soapAction="urn:echo"/><w:input><s:body use="literal"/></w:input>
   <w:output><s:body use="literal"/></w:output></w:operation></w:binding>
 <w:binding name="B12" type="t:P"><s12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
  <w:operation name="echo"><s12:operation soapAction="urn:echo"/><w:input><s12:body use="literal"/></w:input>
   <w:output><s12:body use="literal"/></w:output></w:operation></w:binding>
 <w:service name="S"><w:port name="Port11" binding="t:B11"><s:address location="http://example.invalid/service11"/></w:port><w:port name="Port12" binding="t:B12"><s12:address location="http://example.invalid/service12"/></w:port></w:service>
</w:definitions>
