<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o.
     MTOM/XOP output contract: literal base64Binary content in document, RPC, header and SwA messages, with
     encoded, list and union values that stay inline. -->
<definitions name="MtomOutput" targetNamespace="urn:mtom-output"
    xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:mtom-output"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:xmime="http://www.w3.org/2005/05/xmlmime">
  <types>
    <xsd:schema targetNamespace="http://www.w3.org/2005/05/xmlmime">
      <xsd:attribute name="contentType" type="xsd:string"/>
    </xsd:schema>
    <xsd:schema targetNamespace="urn:mtom-output" elementFormDefault="qualified">
      <xsd:import namespace="http://www.w3.org/2005/05/xmlmime"/>
      <xsd:simpleType name="Digest">
        <xsd:restriction base="xsd:base64Binary"><xsd:length value="4"/></xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="BinaryList"><xsd:list itemType="xsd:base64Binary"/></xsd:simpleType>
      <xsd:simpleType name="IntOrBinary"><xsd:union memberTypes="xsd:int xsd:base64Binary"/></xsd:simpleType>
      <xsd:complexType name="Typed">
        <xsd:simpleContent>
          <xsd:extension base="xsd:base64Binary">
            <xsd:attribute ref="xmime:contentType"/>
          </xsd:extension>
        </xsd:simpleContent>
      </xsd:complexType>
      <xsd:element name="upload">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="data" type="xsd:base64Binary" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="digest" type="tns:Digest" minOccurs="0"/>
            <xsd:element name="typed" type="tns:Typed" minOccurs="0"/>
            <xsd:element name="list" type="tns:BinaryList" minOccurs="0"/>
            <xsd:element name="choice" type="tns:IntOrBinary" minOccurs="0"/>
            <xsd:element name="any" type="xsd:anyType" minOccurs="0"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="token" type="xsd:base64Binary"/>
    </xsd:schema>
  </types>
  <message name="UploadIn">
    <part name="body" element="tns:upload"/>
  </message>
  <message name="UploadOut">
    <part name="body" element="tns:upload"/>
  </message>
  <message name="RejectedFault">
    <part name="detail" element="tns:token"/>
  </message>
  <message name="TokenHeader">
    <part name="token" element="tns:token"/>
  </message>
  <message name="BlobIn">
    <part name="blob" type="xsd:base64Binary"/>
  </message>
  <message name="BlobOut">
    <part name="blob" type="xsd:base64Binary"/>
  </message>
  <message name="AttachIn">
    <part name="body" element="tns:upload"/>
    <part name="file" type="xsd:base64Binary"/>
    <part name="doc" element="tns:upload"/>
  </message>
  <portType name="Mtom">
    <operation name="upload">
      <input message="tns:UploadIn"/>
      <output message="tns:UploadOut"/>
      <fault name="Rejected" message="tns:RejectedFault"/>
    </operation>
  </portType>
  <portType name="Blob">
    <operation name="blob">
      <input message="tns:BlobIn"/>
      <output message="tns:BlobOut"/>
    </operation>
  </portType>
  <portType name="Attach">
    <operation name="attach">
      <input message="tns:AttachIn"/>
      <output message="tns:UploadOut"/>
    </operation>
  </portType>
  <binding name="Doc11" type="tns:Mtom">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="upload">
      <soap:operation soapAction="urn:mtom-output:upload"/>
      <input>
        <soap:body use="literal"/>
        <soap:header message="tns:TokenHeader" part="token" use="literal"/>
      </input>
      <output><soap:body use="literal"/></output>
      <fault name="Rejected"><soap:fault name="Rejected" use="literal"/></fault>
    </operation>
  </binding>
  <binding name="Doc12" type="tns:Mtom">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="upload">
      <soap12:operation soapAction="urn:mtom-output:upload"/>
      <input><soap12:body use="literal"/></input>
      <output><soap12:body use="literal"/></output>
      <fault name="Rejected"><soap12:fault name="Rejected" use="literal"/></fault>
    </operation>
  </binding>
  <binding name="Rpc11" type="tns:Blob">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="blob">
      <soap:operation soapAction="urn:mtom-output:blob"/>
      <input><soap:body use="literal" namespace="urn:mtom-output"/></input>
      <output><soap:body use="literal" namespace="urn:mtom-output"/></output>
    </operation>
  </binding>
  <binding name="Enc11" type="tns:Blob">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="blob">
      <soap:operation soapAction="urn:mtom-output:blob"/>
      <input><soap:body use="encoded" namespace="urn:mtom-output"
        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
      <output><soap:body use="encoded" namespace="urn:mtom-output"
        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
    </operation>
  </binding>
  <binding name="SwA11" type="tns:Attach">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="attach">
      <soap:operation soapAction="urn:mtom-output:attach"/>
      <input>
        <mime:multipartRelated>
          <mime:part><soap:body parts="body" use="literal"/></mime:part>
          <mime:part><mime:content part="file" type="application/octet-stream"/></mime:part>
          <mime:part><mime:content part="doc" type="text/xml"/></mime:part>
        </mime:multipartRelated>
      </input>
      <output><soap:body use="literal"/></output>
    </operation>
  </binding>
  <service name="MtomOutput">
    <port name="Doc11" binding="tns:Doc11"><soap:address location="http://localhost/mtom"/></port>
    <port name="Doc12" binding="tns:Doc12"><soap12:address location="http://localhost/mtom"/></port>
    <port name="Rpc11" binding="tns:Rpc11"><soap:address location="http://localhost/mtom"/></port>
    <port name="Enc11" binding="tns:Enc11"><soap:address location="http://localhost/mtom"/></port>
    <port name="SwA11" binding="tns:SwA11"><soap:address location="http://localhost/mtom"/></port>
  </service>
</definitions>
