<?xml version="1.0" encoding="UTF-8"?>
<!-- WSDL for testing serializing nillable elements explicitly with xsi:nil="true" -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:tns="urn:qore:test:nil-attribute"
             targetNamespace="urn:qore:test:nil-attribute">
    <types>
        <xs:schema targetNamespace="urn:qore:test:nil-attribute"
                   xmlns="urn:qore:test:nil-attribute" elementFormDefault="qualified">
            <!-- a type declaring no attributes at all -->
            <xs:complexType name="hotline-type">
                <xs:sequence>
                    <xs:element name="hotline-operator-configuration" type="xs:string" nillable="true"
                                minOccurs="0"/>
                    <xs:element name="hotline-user-configuration" type="xs:string" nillable="true" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
            <!-- a type with required content -->
            <xs:complexType name="icb-ruleset-type">
                <xs:sequence>
                    <xs:element name="rule" type="xs:string" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="icb-operator-configuration-type">
                <xs:sequence>
                    <xs:element name="icb-ruleset" type="icb-ruleset-type" nillable="true" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="icb-type">
                <xs:sequence>
                    <xs:element name="icb-operator-configuration" type="icb-operator-configuration-type"
                                minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
            <!-- a type with attributes; an element with xsi:nil="true" can still have attributes -->
            <xs:complexType name="attr-type">
                <xs:sequence>
                    <xs:element name="value" type="xs:string"/>
                </xs:sequence>
                <xs:attribute name="id" type="xs:string" use="required"/>
                <xs:attribute name="count" type="xs:int"/>
            </xs:complexType>
            <!-- a type declaring an attribute named "nil" itself -->
            <xs:complexType name="own-nil-type">
                <xs:sequence>
                    <xs:element name="value" type="xs:string" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="nil" type="xs:string"/>
            </xs:complexType>

            <xs:element name="Req">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="hotline" type="hotline-type" nillable="true" minOccurs="0"/>
                        <xs:element name="incoming-communication-barring" type="icb-type" minOccurs="0"/>
                        <xs:element name="with-attr" type="attr-type" nillable="true" minOccurs="0"/>
                        <xs:element name="own-nil" type="own-nil-type" nillable="true" minOccurs="0"/>
                        <xs:element name="simple" type="xs:string" nillable="true" minOccurs="0"/>
                        <xs:element name="list" type="hotline-type" nillable="true" minOccurs="0"
                                    maxOccurs="unbounded"/>
                        <!-- not nillable: xsi:nil cannot be used -->
                        <xs:element name="not-nillable" type="hotline-type" minOccurs="0"/>
                        <!-- required and nillable: serialized with xsi:nil="true" when no value is given -->
                        <xs:element name="required-nillable" type="hotline-type" nillable="true"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Resp" type="xs:string"/>
        </xs:schema>
    </types>

    <message name="ReqM"><part name="parameters" element="tns:Req"/></message>
    <message name="RespM"><part name="parameters" element="tns:Resp"/></message>

    <portType name="NilAttributePort">
        <operation name="Op">
            <input message="tns:ReqM"/>
            <output message="tns:RespM"/>
        </operation>
    </portType>

    <binding name="NilAttributeBinding" type="tns:NilAttributePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Op">
            <soap:operation soapAction="Op" style="document"/>
            <input><soap:body use="literal"/></input>
            <output><soap:body use="literal"/></output>
        </operation>
    </binding>

    <service name="NilAttributeService">
        <port name="NilAttributePort" binding="tns:NilAttributeBinding">
            <soap:address location="http://localhost:8080/nil-attribute"/>
        </port>
    </service>
</definitions>
