<?xml version="1.0" encoding="UTF-8"?>
<!-- Comprehensive SOAP Test WSDL - Copyright (C) 2026 Qore Technologies, s.r.o. -->
<!-- Tests: MTOM/XOP, RPC/Encoded, SOAP Arrays, Type Inheritance, Corner Cases -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:s="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="http://qore.org/soap-comprehensive-test"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xmime="http://www.w3.org/2005/05/xmlmime"
    xmlns:xop="http://www.w3.org/2004/08/xop/include"
    targetNamespace="http://qore.org/soap-comprehensive-test">

  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://qore.org/soap-comprehensive-test">

      <!-- Import XOP namespace for MTOM -->
      <s:import namespace="http://www.w3.org/2004/08/xop/include"/>

      <!-- ========================================= -->
      <!-- TYPE INHERITANCE - BASE TYPES            -->
      <!-- ========================================= -->

      <!-- Abstract base type for all entities -->
      <s:complexType name="BaseEntity" abstract="true">
        <s:sequence>
          <s:element name="id" type="s:long"/>
          <s:element name="createdAt" type="s:dateTime" minOccurs="0"/>
          <s:element name="modifiedAt" type="s:dateTime" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <!-- Extension: Person extends BaseEntity -->
      <s:complexType name="Person">
        <s:complexContent>
          <s:extension base="tns:BaseEntity">
            <s:sequence>
              <s:element name="firstName" type="s:string"/>
              <s:element name="lastName" type="s:string"/>
              <s:element name="email" type="s:string" minOccurs="0"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>

      <!-- Extension: Employee extends Person (multi-level inheritance) -->
      <s:complexType name="Employee">
        <s:complexContent>
          <s:extension base="tns:Person">
            <s:sequence>
              <s:element name="employeeId" type="s:string"/>
              <s:element name="department" type="s:string"/>
              <s:element name="salary" type="s:decimal" minOccurs="0"/>
              <s:element name="manager" type="tns:Employee" minOccurs="0"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>

      <!-- Extension: Customer extends Person -->
      <s:complexType name="Customer">
        <s:complexContent>
          <s:extension base="tns:Person">
            <s:sequence>
              <s:element name="customerId" type="s:string"/>
              <s:element name="loyaltyPoints" type="s:int" minOccurs="0"/>
              <s:element name="tier" type="tns:CustomerTier" minOccurs="0"/>
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>

      <!-- Enumeration type -->
      <s:simpleType name="CustomerTier">
        <s:restriction base="s:string">
          <s:enumeration value="Bronze"/>
          <s:enumeration value="Silver"/>
          <s:enumeration value="Gold"/>
          <s:enumeration value="Platinum"/>
        </s:restriction>
      </s:simpleType>

      <!-- Restriction: RestrictedString restricts string with pattern -->
      <s:simpleType name="PhoneNumber">
        <s:restriction base="s:string">
          <s:pattern value="\+?[0-9\-\s\(\)]{7,20}"/>
        </s:restriction>
      </s:simpleType>

      <!-- Restriction: ComplexType restriction -->
      <s:complexType name="Address">
        <s:sequence>
          <s:element name="street" type="s:string"/>
          <s:element name="city" type="s:string"/>
          <s:element name="state" type="s:string" minOccurs="0"/>
          <s:element name="postalCode" type="s:string"/>
          <s:element name="country" type="s:string"/>
        </s:sequence>
      </s:complexType>

      <!-- Restriction: USAddress restricts Address -->
      <s:complexType name="USAddress">
        <s:complexContent>
          <s:restriction base="tns:Address">
            <s:sequence>
              <s:element name="street" type="s:string"/>
              <s:element name="city" type="s:string"/>
              <s:element name="state" type="tns:USState"/>
              <s:element name="postalCode" type="tns:USZipCode"/>
              <s:element name="country" type="s:string" fixed="USA"/>
            </s:sequence>
          </s:restriction>
        </s:complexContent>
      </s:complexType>

      <s:simpleType name="USState">
        <s:restriction base="s:string">
          <s:pattern value="[A-Z]{2}"/>
        </s:restriction>
      </s:simpleType>

      <s:simpleType name="USZipCode">
        <s:restriction base="s:string">
          <s:pattern value="[0-9]{5}(-[0-9]{4})?"/>
        </s:restriction>
      </s:simpleType>

      <!-- ========================================= -->
      <!-- SOAP ARRAYS                              -->
      <!-- ========================================= -->

      <!-- Simple array of strings -->
      <s:complexType name="StringArray">
        <s:sequence>
          <s:element name="item" type="s:string" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Array of integers -->
      <s:complexType name="IntArray">
        <s:sequence>
          <s:element name="item" type="s:int" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Array of complex types -->
      <s:complexType name="PersonArray">
        <s:sequence>
          <s:element name="person" type="tns:Person" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Nested arrays (2D array simulation) -->
      <s:complexType name="IntArrayRow">
        <s:sequence>
          <s:element name="col" type="s:int" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="IntMatrix">
        <s:sequence>
          <s:element name="row" type="tns:IntArrayRow" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Array with attributes -->
      <s:complexType name="NamedArray">
        <s:sequence>
          <s:element name="item" type="s:string" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
        <s:attribute name="name" type="s:string"/>
        <s:attribute name="count" type="s:int"/>
      </s:complexType>

      <!-- SOAP-encoded array type (for RPC/Encoded) -->
      <s:complexType name="ArrayOfString">
        <s:complexContent>
          <s:restriction base="soapenc:Array">
            <s:attribute ref="soapenc:arrayType" wsdl:arrayType="s:string[]"/>
          </s:restriction>
        </s:complexContent>
      </s:complexType>

      <s:complexType name="ArrayOfInt">
        <s:complexContent>
          <s:restriction base="soapenc:Array">
            <s:attribute ref="soapenc:arrayType" wsdl:arrayType="s:int[]"/>
          </s:restriction>
        </s:complexContent>
      </s:complexType>

      <!-- ========================================= -->
      <!-- MTOM/XOP TYPES                           -->
      <!-- ========================================= -->

      <!-- Binary content for MTOM -->
      <s:complexType name="BinaryContent">
        <s:sequence>
          <s:element name="filename" type="s:string"/>
          <s:element name="contentType" type="s:string"/>
          <s:element name="data" type="s:base64Binary" xmime:expectedContentTypes="application/octet-stream"/>
        </s:sequence>
      </s:complexType>

      <!-- Multiple binary attachments -->
      <s:complexType name="MultipartMessage">
        <s:sequence>
          <s:element name="subject" type="s:string"/>
          <s:element name="body" type="s:string"/>
          <s:element name="attachment" type="tns:BinaryContent" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Document with embedded binary -->
      <s:complexType name="Document">
        <s:sequence>
          <s:element name="title" type="s:string"/>
          <s:element name="author" type="s:string"/>
          <s:element name="content" type="s:base64Binary"/>
          <s:element name="thumbnail" type="s:base64Binary" minOccurs="0"/>
          <s:element name="signature" type="s:hexBinary" minOccurs="0"/>
        </s:sequence>
        <s:attribute name="version" type="s:int"/>
      </s:complexType>

      <!-- ========================================= -->
      <!-- CORNER CASE TYPES                        -->
      <!-- ========================================= -->

      <!-- Empty complex type -->
      <s:complexType name="EmptyType">
        <s:sequence/>
      </s:complexType>

      <!-- Type with only attributes -->
      <s:complexType name="AttributeOnlyType">
        <s:attribute name="id" type="s:string" use="required"/>
        <s:attribute name="name" type="s:string"/>
        <s:attribute name="active" type="s:boolean" default="true"/>
      </s:complexType>

      <!-- Mixed content type -->
      <s:complexType name="MixedContent" mixed="true">
        <s:sequence>
          <s:element name="bold" type="s:string" minOccurs="0" maxOccurs="unbounded"/>
          <s:element name="italic" type="s:string" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Nillable elements -->
      <s:complexType name="NillableFields">
        <s:sequence>
          <s:element name="requiredField" type="s:string"/>
          <s:element name="optionalField" type="s:string" minOccurs="0"/>
          <s:element name="nillableField" type="s:string" nillable="true"/>
          <s:element name="nillableOptional" type="s:string" nillable="true" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <!-- Choice type -->
      <s:complexType name="PaymentMethod">
        <s:choice>
          <s:element name="creditCard" type="tns:CreditCard"/>
          <s:element name="bankAccount" type="tns:BankAccount"/>
          <s:element name="paypal" type="s:string"/>
        </s:choice>
      </s:complexType>

      <s:complexType name="CreditCard">
        <s:sequence>
          <s:element name="number" type="s:string"/>
          <s:element name="expiry" type="s:string"/>
          <s:element name="cvv" type="s:string"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="BankAccount">
        <s:sequence>
          <s:element name="accountNumber" type="s:string"/>
          <s:element name="routingNumber" type="s:string"/>
        </s:sequence>
      </s:complexType>

      <!-- All compositor (unordered elements) -->
      <s:complexType name="UnorderedData">
        <s:all>
          <s:element name="alpha" type="s:string"/>
          <s:element name="beta" type="s:int"/>
          <s:element name="gamma" type="s:boolean"/>
        </s:all>
      </s:complexType>

      <!-- Deeply nested type -->
      <s:complexType name="Level1">
        <s:sequence>
          <s:element name="value" type="s:string"/>
          <s:element name="level2" type="tns:Level2" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="Level2">
        <s:sequence>
          <s:element name="value" type="s:string"/>
          <s:element name="level3" type="tns:Level3" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="Level3">
        <s:sequence>
          <s:element name="value" type="s:string"/>
          <s:element name="level4" type="tns:Level4" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="Level4">
        <s:sequence>
          <s:element name="value" type="s:string"/>
          <s:element name="level5" type="tns:Level5" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="Level5">
        <s:sequence>
          <s:element name="value" type="s:string"/>
        </s:sequence>
      </s:complexType>

      <!-- Self-referential type (recursive) -->
      <s:complexType name="TreeNode">
        <s:sequence>
          <s:element name="value" type="s:string"/>
          <s:element name="children" type="tns:TreeNode" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
        <s:attribute name="id" type="s:int"/>
      </s:complexType>

      <!-- ========================================= -->
      <!-- GROUPS WITH OCCURRENCE CONSTRAINTS       -->
      <!-- ========================================= -->

      <s:group name="OptionalContactInfo">
        <s:sequence>
          <s:element name="phone" type="tns:PhoneNumber" minOccurs="0"/>
          <s:element name="fax" type="tns:PhoneNumber" minOccurs="0"/>
          <s:element name="mobile" type="tns:PhoneNumber" minOccurs="0"/>
        </s:sequence>
      </s:group>

      <s:group name="RequiredIdentification">
        <s:sequence>
          <s:element name="idType" type="s:string"/>
          <s:element name="idNumber" type="s:string"/>
          <s:element name="issuingCountry" type="s:string"/>
        </s:sequence>
      </s:group>

      <!-- Nested attribute groups -->
      <s:attributeGroup name="AuditAttrs">
        <s:attribute name="createdBy" type="s:string"/>
        <s:attribute name="modifiedBy" type="s:string"/>
      </s:attributeGroup>

      <s:attributeGroup name="FullAuditAttrs">
        <s:attributeGroup ref="tns:AuditAttrs"/>
        <s:attribute name="createdAt" type="s:dateTime"/>
        <s:attribute name="modifiedAt" type="s:dateTime"/>
      </s:attributeGroup>

      <!-- Type using groups with minOccurs="0" -->
      <s:complexType name="ContactRecord">
        <s:sequence>
          <s:element name="name" type="s:string"/>
          <s:group ref="tns:OptionalContactInfo" minOccurs="0"/>
          <s:element name="address" type="tns:Address" minOccurs="0"/>
        </s:sequence>
        <s:attributeGroup ref="tns:FullAuditAttrs"/>
      </s:complexType>

      <!-- ========================================= -->
      <!-- REQUEST/RESPONSE ELEMENTS                -->
      <!-- ========================================= -->

      <!-- Type inheritance test -->
      <s:element name="CreatePerson">
        <s:complexType>
          <s:sequence>
            <s:element name="person" type="tns:Person"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="CreatePersonResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="id" type="s:long"/>
            <s:element name="success" type="s:boolean"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="CreateEmployee">
        <s:complexType>
          <s:sequence>
            <s:element name="employee" type="tns:Employee"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="CreateCustomer">
        <s:complexType>
          <s:sequence>
            <s:element name="customer" type="tns:Customer"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- Array test -->
      <s:element name="ProcessStrings">
        <s:complexType>
          <s:sequence>
            <s:element name="strings" type="tns:StringArray"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="ProcessStringsResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="count" type="s:int"/>
            <s:element name="concatenated" type="s:string"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="ProcessMatrix">
        <s:complexType>
          <s:sequence>
            <s:element name="matrix" type="tns:IntMatrix"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="ProcessMatrixResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="rows" type="s:int"/>
            <s:element name="cols" type="s:int"/>
            <s:element name="sum" type="s:long"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- MTOM test -->
      <s:element name="UploadDocument">
        <s:complexType>
          <s:sequence>
            <s:element name="document" type="tns:Document"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="UploadDocumentResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="documentId" type="s:string"/>
            <s:element name="size" type="s:long"/>
            <s:element name="checksum" type="s:string"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="SendMultipart">
        <s:complexType>
          <s:sequence>
            <s:element name="message" type="tns:MultipartMessage"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- Corner cases test -->
      <s:element name="TestCornerCases">
        <s:complexType>
          <s:sequence>
            <s:element name="empty" type="tns:EmptyType" minOccurs="0"/>
            <s:element name="attrOnly" type="tns:AttributeOnlyType" minOccurs="0"/>
            <s:element name="nillable" type="tns:NillableFields" minOccurs="0"/>
            <s:element name="payment" type="tns:PaymentMethod" minOccurs="0"/>
            <s:element name="unordered" type="tns:UnorderedData" minOccurs="0"/>
            <s:element name="nested" type="tns:Level1" minOccurs="0"/>
            <s:element name="tree" type="tns:TreeNode" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="TestCornerCasesResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="success" type="s:boolean"/>
            <s:element name="message" type="s:string" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- Contact record with groups -->
      <s:element name="CreateContact">
        <s:complexType>
          <s:sequence>
            <s:element name="contact" type="tns:ContactRecord"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- RPC-style messages (for encoded binding) -->
      <s:element name="echoStrings">
        <s:complexType>
          <s:sequence>
            <s:element name="input" type="tns:ArrayOfString"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="echoStringsResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="return" type="tns:ArrayOfString"/>
          </s:sequence>
        </s:complexType>
      </s:element>

    </s:schema>
  </wsdl:types>

  <!-- ========================================= -->
  <!-- WSDL MESSAGES                            -->
  <!-- ========================================= -->

  <!-- Document/literal messages -->
  <wsdl:message name="CreatePersonRequest">
    <wsdl:part name="body" element="tns:CreatePerson"/>
  </wsdl:message>

  <wsdl:message name="CreatePersonResponse">
    <wsdl:part name="body" element="tns:CreatePersonResponse"/>
  </wsdl:message>

  <wsdl:message name="CreateEmployeeRequest">
    <wsdl:part name="body" element="tns:CreateEmployee"/>
  </wsdl:message>

  <wsdl:message name="CreateCustomerRequest">
    <wsdl:part name="body" element="tns:CreateCustomer"/>
  </wsdl:message>

  <wsdl:message name="ProcessStringsRequest">
    <wsdl:part name="body" element="tns:ProcessStrings"/>
  </wsdl:message>

  <wsdl:message name="ProcessStringsResponse">
    <wsdl:part name="body" element="tns:ProcessStringsResponse"/>
  </wsdl:message>

  <wsdl:message name="ProcessMatrixRequest">
    <wsdl:part name="body" element="tns:ProcessMatrix"/>
  </wsdl:message>

  <wsdl:message name="ProcessMatrixResponse">
    <wsdl:part name="body" element="tns:ProcessMatrixResponse"/>
  </wsdl:message>

  <wsdl:message name="UploadDocumentRequest">
    <wsdl:part name="body" element="tns:UploadDocument"/>
  </wsdl:message>

  <wsdl:message name="UploadDocumentResponse">
    <wsdl:part name="body" element="tns:UploadDocumentResponse"/>
  </wsdl:message>

  <wsdl:message name="SendMultipartRequest">
    <wsdl:part name="body" element="tns:SendMultipart"/>
  </wsdl:message>

  <wsdl:message name="TestCornerCasesRequest">
    <wsdl:part name="body" element="tns:TestCornerCases"/>
  </wsdl:message>

  <wsdl:message name="TestCornerCasesResponse">
    <wsdl:part name="body" element="tns:TestCornerCasesResponse"/>
  </wsdl:message>

  <wsdl:message name="CreateContactRequest">
    <wsdl:part name="body" element="tns:CreateContact"/>
  </wsdl:message>

  <!-- RPC/Encoded messages -->
  <wsdl:message name="EchoStringsRequest">
    <wsdl:part name="input" type="tns:ArrayOfString"/>
  </wsdl:message>

  <wsdl:message name="EchoStringsResponse">
    <wsdl:part name="return" type="tns:ArrayOfString"/>
  </wsdl:message>

  <!-- ========================================= -->
  <!-- WSDL PORT TYPES                          -->
  <!-- ========================================= -->

  <!-- Document/literal port type -->
  <wsdl:portType name="ComprehensivePortType">
    <wsdl:operation name="createPerson">
      <wsdl:input message="tns:CreatePersonRequest"/>
      <wsdl:output message="tns:CreatePersonResponse"/>
    </wsdl:operation>
    <wsdl:operation name="createEmployee">
      <wsdl:input message="tns:CreateEmployeeRequest"/>
      <wsdl:output message="tns:CreatePersonResponse"/>
    </wsdl:operation>
    <wsdl:operation name="createCustomer">
      <wsdl:input message="tns:CreateCustomerRequest"/>
      <wsdl:output message="tns:CreatePersonResponse"/>
    </wsdl:operation>
    <wsdl:operation name="processStrings">
      <wsdl:input message="tns:ProcessStringsRequest"/>
      <wsdl:output message="tns:ProcessStringsResponse"/>
    </wsdl:operation>
    <wsdl:operation name="processMatrix">
      <wsdl:input message="tns:ProcessMatrixRequest"/>
      <wsdl:output message="tns:ProcessMatrixResponse"/>
    </wsdl:operation>
    <wsdl:operation name="uploadDocument">
      <wsdl:input message="tns:UploadDocumentRequest"/>
      <wsdl:output message="tns:UploadDocumentResponse"/>
    </wsdl:operation>
    <wsdl:operation name="sendMultipart">
      <wsdl:input message="tns:SendMultipartRequest"/>
      <wsdl:output message="tns:TestCornerCasesResponse"/>
    </wsdl:operation>
    <wsdl:operation name="testCornerCases">
      <wsdl:input message="tns:TestCornerCasesRequest"/>
      <wsdl:output message="tns:TestCornerCasesResponse"/>
    </wsdl:operation>
    <wsdl:operation name="createContact">
      <wsdl:input message="tns:CreateContactRequest"/>
      <wsdl:output message="tns:CreatePersonResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <!-- RPC port type -->
  <wsdl:portType name="RpcPortType">
    <wsdl:operation name="echoStrings">
      <wsdl:input message="tns:EchoStringsRequest"/>
      <wsdl:output message="tns:EchoStringsResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <!-- ========================================= -->
  <!-- WSDL BINDINGS                            -->
  <!-- ========================================= -->

  <!-- SOAP 1.2 Document/Literal binding -->
  <wsdl:binding name="ComprehensiveSoap12Binding" type="tns:ComprehensivePortType">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="createPerson">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/createPerson"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createEmployee">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/createEmployee"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createCustomer">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/createCustomer"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="processStrings">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/processStrings"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="processMatrix">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/processMatrix"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="uploadDocument">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/uploadDocument"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="sendMultipart">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/sendMultipart"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="testCornerCases">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/testCornerCases"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createContact">
      <soap12:operation soapAction="http://qore.org/soap-comprehensive-test/createContact"/>
      <wsdl:input><soap12:body use="literal"/></wsdl:input>
      <wsdl:output><soap12:body use="literal"/></wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <!-- SOAP 1.1 Document/Literal binding -->
  <wsdl:binding name="ComprehensiveSoap11Binding" type="tns:ComprehensivePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="createPerson">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/createPerson"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createEmployee">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/createEmployee"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createCustomer">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/createCustomer"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="processStrings">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/processStrings"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="processMatrix">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/processMatrix"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="uploadDocument">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/uploadDocument"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="sendMultipart">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/sendMultipart"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="testCornerCases">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/testCornerCases"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createContact">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/createContact"/>
      <wsdl:input><soap:body use="literal"/></wsdl:input>
      <wsdl:output><soap:body use="literal"/></wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <!-- SOAP 1.1 RPC/Encoded binding -->
  <wsdl:binding name="RpcEncodedBinding" type="tns:RpcPortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <wsdl:operation name="echoStrings">
      <soap:operation soapAction="http://qore.org/soap-comprehensive-test/echoStrings"/>
      <wsdl:input>
        <soap:body use="encoded" namespace="http://qore.org/soap-comprehensive-test"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="encoded" namespace="http://qore.org/soap-comprehensive-test"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <!-- ========================================= -->
  <!-- WSDL SERVICE                             -->
  <!-- ========================================= -->

  <wsdl:service name="ComprehensiveTestService">
    <wsdl:port name="ComprehensiveSoap12Port" binding="tns:ComprehensiveSoap12Binding">
      <soap12:address location="http://localhost:8001/SOAP/comprehensive"/>
    </wsdl:port>
    <wsdl:port name="ComprehensiveSoap11Port" binding="tns:ComprehensiveSoap11Binding">
      <soap:address location="http://localhost:8001/SOAP/comprehensive11"/>
    </wsdl:port>
    <wsdl:port name="RpcEncodedPort" binding="tns:RpcEncodedBinding">
      <soap:address location="http://localhost:8001/SOAP/rpc"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
