<?xml version="1.0" encoding="UTF-8"?>
<!-- XSD Facets and Types Test WSDL - Copyright (C) 2026 Qore Technologies, s.r.o. -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:s="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="http://qore.org/xsd-facets-test"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://qore.org/xsd-facets-test">

  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://qore.org/xsd-facets-test">

      <!-- ========================================= -->
      <!-- XSD Restriction Facets - String Facets   -->
      <!-- ========================================= -->

      <!-- Pattern facet - regex validation -->
      <s:simpleType name="PatternString">
        <s:restriction base="s:string">
          <s:pattern value="[A-Z]{2}[0-9]{4}"/>
        </s:restriction>
      </s:simpleType>

      <!-- Multiple patterns in one restriction; XSD 1.0 part 2 4.3.4.3 combines them with "|" -->
      <s:simpleType name="MultiPatternString">
        <s:restriction base="s:string">
          <s:pattern value="[A-Z].*"/>
          <s:pattern value=".*[0-9]"/>
        </s:restriction>
      </s:simpleType>

      <!-- issue #5411: a pattern with a top-level alternation must be anchored as a whole -->
      <s:simpleType name="AltPatternString">
        <s:restriction base="s:string">
          <s:pattern value="aaa|bbb"/>
        </s:restriction>
      </s:simpleType>

      <!-- issue #5411: patterns declared in different derivation steps are intersected -->
      <s:simpleType name="DerivedPatternBase">
        <s:restriction base="s:string">
          <s:pattern value="[a-z]+"/>
        </s:restriction>
      </s:simpleType>
      <s:simpleType name="DerivedPatternString">
        <s:restriction base="tns:DerivedPatternBase">
          <s:pattern value=".{3}"/>
        </s:restriction>
      </s:simpleType>

      <!-- 16 sibling patterns, one per IPv6 textual form; modelled on a vendor-supplied schema -->
      <s:simpleType name="IpV6AddressString">
        <s:restriction base="s:string">
          <s:pattern value=".*[$][0-9A-Fa-f]{1,4}(:[0-9A-Fa-f]{1,4}){7}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]:(:[0-9A-Fa-f]{1,4}){1,7}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,6}(:[0-9A-Fa-f]{1,4}){1}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,5}(:[0-9A-Fa-f]{1,4}){1,2}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,4}(:[0-9A-Fa-f]{1,4}){1,3}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,3}(:[0-9A-Fa-f]{1,4}){1,4}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,2}(:[0-9A-Fa-f]{1,4}){1,5}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1}(:[0-9A-Fa-f]{1,4}){1,6}([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,7}:([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9a-fA-F]{1,4}:){6,6}((25[0-5]|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9])[.]){3,3}(((25[0-5])|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9]))([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]::([0-9a-fA-F]{1,4}:){0,5}((25[0-5]|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9])[.]){3,3}(((25[0-5])|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9]))([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,4}(:[0-9A-Fa-f]{1,4}){1}:((25[0-5]|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9])[.]){3,3}(((25[0-5])|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9]))([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,3}(:[0-9A-Fa-f]{1,4}){1,2}:((25[0-5]|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9])[.]){3,3}(((25[0-5])|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9]))([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1,2}(:[0-9A-Fa-f]{1,4}){1,3}:((25[0-5]|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9])[.]){3,3}(((25[0-5])|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9]))([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9A-Fa-f]{1,4}:){1}(:[0-9A-Fa-f]{1,4}){1,4}:((25[0-5]|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9])[.]){3,3}(((25[0-5])|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9]))([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
          <s:pattern value=".*[$]([0-9a-fA-F]{1,4}:){1,5}:((25[0-5]|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9])[.]){3,3}(((25[0-5])|(2[0-4][0-9])|(1[0-9][0-9])|[1-9]?[0-9]))([/]((12[0-8]|(1[0-1][0-9])|([1-9][0-9]|[0-9]))))?"/>
        </s:restriction>
      </s:simpleType>


      <!-- Length facet - exact length -->
      <s:simpleType name="FixedLengthString">
        <s:restriction base="s:string">
          <s:length value="10"/>
        </s:restriction>
      </s:simpleType>

      <!-- MinLength facet -->
      <s:simpleType name="MinLengthString">
        <s:restriction base="s:string">
          <s:minLength value="5"/>
        </s:restriction>
      </s:simpleType>

      <!-- MaxLength facet -->
      <s:simpleType name="MaxLengthString">
        <s:restriction base="s:string">
          <s:maxLength value="20"/>
        </s:restriction>
      </s:simpleType>

      <!-- Combined length constraints -->
      <s:simpleType name="BoundedLengthString">
        <s:restriction base="s:string">
          <s:minLength value="3"/>
          <s:maxLength value="50"/>
        </s:restriction>
      </s:simpleType>

      <!-- WhiteSpace facet - for completeness -->
      <s:simpleType name="CollapsedString">
        <s:restriction base="s:string">
          <s:whiteSpace value="collapse"/>
        </s:restriction>
      </s:simpleType>

      <!-- ========================================= -->
      <!-- XSD Restriction Facets - Numeric Facets  -->
      <!-- ========================================= -->

      <!-- MinInclusive facet -->
      <s:simpleType name="PositiveInt">
        <s:restriction base="s:int">
          <s:minInclusive value="1"/>
        </s:restriction>
      </s:simpleType>

      <!-- MaxInclusive facet -->
      <s:simpleType name="PercentageInt">
        <s:restriction base="s:int">
          <s:minInclusive value="0"/>
          <s:maxInclusive value="100"/>
        </s:restriction>
      </s:simpleType>

      <!-- MinExclusive facet -->
      <s:simpleType name="StrictlyPositiveDecimal">
        <s:restriction base="s:decimal">
          <s:minExclusive value="0"/>
        </s:restriction>
      </s:simpleType>

      <!-- MaxExclusive facet -->
      <s:simpleType name="BelowOneDecimal">
        <s:restriction base="s:decimal">
          <s:minInclusive value="0"/>
          <s:maxExclusive value="1"/>
        </s:restriction>
      </s:simpleType>

      <!-- TotalDigits facet -->
      <s:simpleType name="FourDigitNumber">
        <s:restriction base="s:decimal">
          <s:totalDigits value="4"/>
        </s:restriction>
      </s:simpleType>

      <!-- FractionDigits facet -->
      <s:simpleType name="TwoDecimalPlaces">
        <s:restriction base="s:decimal">
          <s:fractionDigits value="2"/>
        </s:restriction>
      </s:simpleType>

      <!-- Combined precision facets -->
      <s:simpleType name="CurrencyAmount">
        <s:restriction base="s:decimal">
          <s:totalDigits value="10"/>
          <s:fractionDigits value="2"/>
          <s:minInclusive value="0"/>
        </s:restriction>
      </s:simpleType>

      <!-- ========================================= -->
      <!-- XSD List Type                            -->
      <!-- ========================================= -->

      <s:simpleType name="IntList">
        <s:list itemType="s:int"/>
      </s:simpleType>

      <s:simpleType name="StringList">
        <s:list itemType="s:string"/>
      </s:simpleType>

      <s:simpleType name="TokenList">
        <s:list itemType="s:token"/>
      </s:simpleType>

      <!-- List with restriction on item type (commented out for now)
      <s:simpleType name="PositiveIntList">
        <s:list itemType="tns:PositiveInt"/>
      </s:simpleType>
      -->

      <!-- ========================================= -->
      <!-- XSD Duration Type                        -->
      <!-- ========================================= -->

      <s:element name="DurationElement" type="s:duration"/>

      <!-- ========================================= -->
      <!-- XSD Partial Date Types (gYear, etc.)     -->
      <!-- ========================================= -->

      <s:element name="YearElement" type="s:gYear"/>
      <s:element name="YearMonthElement" type="s:gYearMonth"/>
      <s:element name="MonthDayElement" type="s:gMonthDay"/>
      <s:element name="MonthElement" type="s:gMonth"/>
      <s:element name="DayElement" type="s:gDay"/>

      <!-- ========================================= -->
      <!-- XSD Float/Double Types                   -->
      <!-- ========================================= -->

      <s:element name="FloatElement" type="s:float"/>
      <s:element name="DoubleElement" type="s:double"/>

      <!-- Float with facets -->
      <s:simpleType name="PositiveFloat">
        <s:restriction base="s:float">
          <s:minExclusive value="0"/>
        </s:restriction>
      </s:simpleType>

      <!-- ========================================= -->
      <!-- XSD Element Groups                       -->
      <!-- ========================================= -->

      <s:group name="AddressGroup">
        <s:sequence>
          <s:element name="street" type="s:string"/>
          <s:element name="city" type="s:string"/>
          <s:element name="zipCode" type="s:string"/>
          <s:element name="country" type="s:string"/>
        </s:sequence>
      </s:group>

      <s:group name="PersonNameGroup">
        <s:sequence>
          <s:element name="firstName" type="s:string"/>
          <s:element name="lastName" type="s:string"/>
        </s:sequence>
      </s:group>

      <!-- ========================================= -->
      <!-- XSD Attribute Groups                     -->
      <!-- ========================================= -->

      <s:attributeGroup name="TimestampAttrs">
        <s:attribute name="createdAt" type="s:dateTime" use="optional"/>
        <s:attribute name="modifiedAt" type="s:dateTime" use="optional"/>
      </s:attributeGroup>

      <s:attributeGroup name="VersionAttrs">
        <s:attribute name="version" type="s:int" use="required"/>
        <s:attribute name="deprecated" type="s:boolean" use="optional"/>
      </s:attributeGroup>

      <!-- ========================================= -->
      <!-- Complex Types Using Groups               -->
      <!-- ========================================= -->

      <s:complexType name="PersonAddress">
        <s:sequence>
          <s:group ref="tns:PersonNameGroup"/>
          <s:group ref="tns:AddressGroup"/>
        </s:sequence>
        <s:attributeGroup ref="tns:TimestampAttrs"/>
      </s:complexType>

      <s:complexType name="VersionedDocument">
        <s:sequence>
          <s:element name="title" type="s:string"/>
          <s:element name="content" type="s:string"/>
        </s:sequence>
        <s:attributeGroup ref="tns:VersionAttrs"/>
      </s:complexType>

      <!-- ========================================= -->
      <!-- Test Elements Using Faceted Types        -->
      <!-- ========================================= -->

      <s:element name="TestFacets">
        <s:complexType>
          <s:sequence>
            <!-- String facets -->
            <s:element name="patternStr" type="tns:PatternString" minOccurs="0"/>
            <s:element name="multiPatternStr" type="tns:MultiPatternString" minOccurs="0"/>
            <s:element name="altPatternStr" type="tns:AltPatternString" minOccurs="0"/>
            <s:element name="derivedPatternStr" type="tns:DerivedPatternString" minOccurs="0"/>
            <s:element name="ipv6Str" type="tns:IpV6AddressString" minOccurs="0"/>
            <s:element name="fixedLenStr" type="tns:FixedLengthString" minOccurs="0"/>
            <s:element name="minLenStr" type="tns:MinLengthString" minOccurs="0"/>
            <s:element name="maxLenStr" type="tns:MaxLengthString" minOccurs="0"/>
            <s:element name="boundedStr" type="tns:BoundedLengthString" minOccurs="0"/>

            <!-- Numeric facets -->
            <s:element name="positiveInt" type="tns:PositiveInt" minOccurs="0"/>
            <s:element name="percentInt" type="tns:PercentageInt" minOccurs="0"/>
            <s:element name="strictPosDecimal" type="tns:StrictlyPositiveDecimal" minOccurs="0"/>
            <s:element name="belowOneDecimal" type="tns:BelowOneDecimal" minOccurs="0"/>
            <s:element name="fourDigitNum" type="tns:FourDigitNumber" minOccurs="0"/>
            <s:element name="twoDecimalPlaces" type="tns:TwoDecimalPlaces" minOccurs="0"/>
            <s:element name="currencyAmount" type="tns:CurrencyAmount" minOccurs="0"/>

            <!-- List types -->
            <s:element name="intList" type="tns:IntList" minOccurs="0"/>
            <s:element name="stringList" type="tns:StringList" minOccurs="0"/>
            <!-- Commented out: <s:element name="positiveIntList" type="tns:PositiveIntList" minOccurs="0"/> -->

            <!-- Duration -->
            <s:element name="duration" type="s:duration" minOccurs="0"/>

            <!-- Partial dates -->
            <s:element name="gYear" type="s:gYear" minOccurs="0"/>
            <s:element name="gYearMonth" type="s:gYearMonth" minOccurs="0"/>
            <s:element name="gMonthDay" type="s:gMonthDay" minOccurs="0"/>
            <s:element name="gMonth" type="s:gMonth" minOccurs="0"/>
            <s:element name="gDay" type="s:gDay" minOccurs="0"/>

            <!-- Float/double -->
            <s:element name="floatVal" type="s:float" minOccurs="0"/>
            <s:element name="doubleVal" type="s:double" minOccurs="0"/>
            <s:element name="positiveFloat" type="tns:PositiveFloat" minOccurs="0"/>

            <!-- Integer types -->
            <s:element name="byteVal" type="s:byte" minOccurs="0"/>
            <s:element name="intVal" type="s:int" minOccurs="0"/>

            <!-- Date/time types -->
            <s:element name="dateVal" type="s:date" minOccurs="0"/>
            <s:element name="dateTimeVal" type="s:dateTime" minOccurs="0"/>
            <s:element name="timeVal" type="s:time" minOccurs="0"/>

            <!-- String-derived types -->
            <s:element name="anyURIVal" type="s:anyURI" minOccurs="0"/>
            <s:element name="languageVal" type="s:language" minOccurs="0"/>
            <s:element name="ncNameVal" type="s:NCName" minOccurs="0"/>
            <s:element name="nmTokenVal" type="s:NMTOKEN" minOccurs="0"/>
            <s:element name="nameVal" type="s:Name" minOccurs="0"/>
            <s:element name="idVal" type="s:ID" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="TestFacetsResult">
        <s:complexType>
          <s:sequence>
            <s:element name="success" type="s:boolean"/>
            <s:element name="message" type="s:string" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- Element using groups -->
      <s:element name="PersonWithAddress" type="tns:PersonAddress"/>

      <!-- MTOM/XOP Test Elements -->
      <s:element name="BinaryData">
        <s:complexType>
          <s:sequence>
            <s:element name="name" type="s:string"/>
            <s:element name="content" type="s:base64Binary"/>
            <s:element name="checksum" type="s:hexBinary" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="BinaryDataResult">
        <s:complexType>
          <s:sequence>
            <s:element name="received" type="s:boolean"/>
            <s:element name="size" type="s:int"/>
          </s:sequence>
        </s:complexType>
      </s:element>

    </s:schema>
  </wsdl:types>

  <!-- ========================================= -->
  <!-- WSDL Messages                            -->
  <!-- ========================================= -->

  <wsdl:message name="TestFacetsRequest">
    <wsdl:part name="body" element="tns:TestFacets"/>
  </wsdl:message>

  <wsdl:message name="TestFacetsResponse">
    <wsdl:part name="body" element="tns:TestFacetsResult"/>
  </wsdl:message>

  <wsdl:message name="PersonAddressRequest">
    <wsdl:part name="body" element="tns:PersonWithAddress"/>
  </wsdl:message>

  <wsdl:message name="BinaryDataRequest">
    <wsdl:part name="body" element="tns:BinaryData"/>
  </wsdl:message>

  <wsdl:message name="BinaryDataResponse">
    <wsdl:part name="body" element="tns:BinaryDataResult"/>
  </wsdl:message>

  <!-- ========================================= -->
  <!-- WSDL Port Type                           -->
  <!-- ========================================= -->

  <wsdl:portType name="XsdFacetsPortType">
    <wsdl:operation name="testFacets">
      <wsdl:input message="tns:TestFacetsRequest"/>
      <wsdl:output message="tns:TestFacetsResponse"/>
    </wsdl:operation>
    <wsdl:operation name="testPersonAddress">
      <wsdl:input message="tns:PersonAddressRequest"/>
      <wsdl:output message="tns:TestFacetsResponse"/>
    </wsdl:operation>
    <wsdl:operation name="uploadBinaryData">
      <wsdl:input message="tns:BinaryDataRequest"/>
      <wsdl:output message="tns:BinaryDataResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <!-- ========================================= -->
  <!-- WSDL Bindings                            -->
  <!-- ========================================= -->

  <wsdl:binding name="XsdFacetsSoap12Binding" type="tns:XsdFacetsPortType">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="testFacets">
      <soap12:operation soapAction="http://qore.org/xsd-facets-test/testFacets"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="testPersonAddress">
      <soap12:operation soapAction="http://qore.org/xsd-facets-test/testPersonAddress"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="uploadBinaryData">
      <soap12:operation soapAction="http://qore.org/xsd-facets-test/uploadBinaryData"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <!-- ========================================= -->
  <!-- WSDL Service                             -->
  <!-- ========================================= -->

  <wsdl:service name="XsdFacetsTestService">
    <wsdl:port name="XsdFacetsSoap12Port" binding="tns:XsdFacetsSoap12Binding">
      <soap12:address location="http://localhost:8001/SOAP/xsd-facets"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
