# -*- mode: qore; indent-tabs-mode: nil -*-
#! Qore SoapRequestDataProvider module definition

/** SoapRequestDataProvider.qc Copyright 2019 - 2022 Qore Technologies, s.r.o.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#! contains all public definitions in the SoapRequestDataProvider module
public namespace SoapDataProvider {
#! The Soap data provider class
public class SoapRequestDataProvider inherits SoapDataProviderBase {
    public {
        #! The SOAP client object for API calls
        *SoapClient soapclient;

        #! If the request supports a list of hashes in the response and therefore the record API
        *hash<string, AbstractDataField> record_type;
    }

    #! Creates the object from the arguments
    constructor(WebService webservice, *SoapClient soapclient, WSOperation op)
            : SoapDataProviderBase(webservice, op) {
        self.soapclient = soapclient;
        record_type = getRecordTypeIntern();
    }

    #! Returns the data provider name
    string getName() {
        return op.name;
    }

    #! Returns data provider info
    hash<DataProviderInfo> getInfo() {
        hash<DataProviderInfo> rv({
            "name": getName(),
            "supports_read": True,
            "supports_request": True,
            "has_record": exists record_type,
        });
        rv += getStaticInfoImpl();
        return rv;
    }

    #! Returns the description of the record type, if any
    /** Returns the record type description for any successful response
    */
    private *hash<string, AbstractDataField> getRecordTypeImpl(*hash<auto> search_options) {
        return record_type;
    }

    #! Returns the description of a successful request message, if any
    private *AbstractDataProviderType getRequestTypeImpl() {
        if (op.input) {
            return op.input.getDataProviderType();
        }
    }

    #! Returns the description of a response message, if this object represents a response message
    /** If the object is a request message, then any successful response message should be returned here as well

        @return the response type for this response message

        @throw INVALID-OPERATION the data provider does not support the request API
    */
    private *AbstractDataProviderType getResponseTypeImpl() {
        if (op.output) {
            return op.output.getDataProviderType();
        }
    }

    #! Returns a hash of error responses, if any
    private *hash<string, AbstractDataProviderType> getErrorResponseTypesImpl() {
        return cast<*hash<string, AbstractDataProviderType>>(map {
            $1.key: $1.value.getDataProviderType(),
        }, op.getFaultMessages().pairIterator());
    }

    #! Makes a request and returned the response
    /** @param req the request to serialize and make according to the request type
        @param request_options the request options; will be processed by validateRequestOptions()

        @return the response to the request
    */
    private auto doRequestImpl(auto req, *hash<auto> request_options) {
        return doRequestIntern(req, request_options);
    }

    #! Returns an iterator for zero or more records matching the search options
    /** @param req the request to serialize and make according to the request type
        @param where_cond the search criteria
        @param search_options the search options after processing by validateSearchOptions()

        This will execute the request and perform a default search on any record(s) returned

        @throw SWAGGER-SEARCH-ERROR the response type exists but is not list or hash and therefore does not support
        searching
    */
    private AbstractDataProviderRecordIterator requestSearchRecordsImpl(auto req, *hash<auto> where_cond,
            *hash<auto> search_options) {
        auto resp = doRequestIntern(req);
        if (resp.response) {
            resp = resp.response;
        }
        # return an iterator for the result
        AbstractIterator i;
        switch (resp.typeCode()) {
            case NT_HASH:
            case NT_NOTHING:
                i = new SingleValueIterator(resp);
                break;
            case NT_LIST:
                i = new ListIterator(resp);
                break;
            default:
                throw "SOAP-SEARCH-ERROR", sprintf("the response has type %y, which does not support searching",
                    resp.type());
                break;
        }
        return new DefaultRecordIterator(i, where_cond, search_options);
    }

    #! Returns an iterator for zero or more records matching the search options
    /** @param where_cond the search criteria
        @param search_options the search options after processing by validateSearchOptions()

        This will execute the request and perform a default search on any record(s) returned
    */
    private AbstractDataProviderRecordIterator searchRecordsImpl(*hash<auto> where_cond, *hash<auto> search_options) {
        return requestSearchRecordsImpl(search_options.request, where_cond, search_options - "request");
    }

    #! Makes a REST request and returns the response
    private auto doRequestIntern(auto req, *hash<auto> options) {
        SoapClient soap = getSoapClient();
        # make the call
        return soap.callOperation(op.name, req, options);
    }

    #! Returns a REST client for HTTP operations
    private SoapClient getSoapClient() {
        if (!soapclient) {
            soapclient = new SoapClient({
                "wsdl": webservice,
            });
        }
        return soapclient;
    }

    #! Returns data provider static info
    private hash<DataProviderInfo> getStaticInfoImpl() {
        hash<DataProviderInfo> rv = SoapDataProvider::ProviderInfo - "constructor_options";
        rv += {
            "supports_read": exists record_type,
            "supports_request": True,
            "has_record": exists record_type,
            "search_options": GenericRecordSearchOptions{"requires_result", "max_records"} + {
                "request": <DataProviderOptionInfo>{
                    "display_name": "Request",
                    "short_desc": "The arguments to the SOAP request",
                    "type": AbstractDataProviderTypeMap."any",
                    "desc": "The arguments to the SOAP request",
                },
            },
        };
        rv.request_options = rv.search_options = getApiOptions();
        return rv;
    }

    #! Returns API options for the current operation
    private *hash<string, hash<DataProviderOptionInfo>> getApiOptions() {
        return {
            "soap_header": <DataProviderOptionInfo>{
                "display_name": "SOAP Headers",
                "short_desc": "SOAP headers to use in the message",
                "type": new HashDataType(),
                "desc": "A hash giving SOAP header information, if required by the message",
            },
            "http_header": <DataProviderOptionInfo>{
                "display_name": "HTTP Headers",
                "short_desc": "HTTP headers to send in the message",
                "type": new HashDataType(),
                "desc": "A hash giving HTTP header information to include in the message (does not override "
                    "automatically-generated SOAP message headers)",
            },
            "xml_opts": <DataProviderOptionInfo>{
                "display_name": "XML Generation Options",
                "short_desc": "XML generation options",
                "type": new QoreIntDataType(),
                "desc": "An integer XML generation option code",
            },
            "soapaction": <DataProviderOptionInfo>{
                "display_name": "SOAP Action",
                "short_desc": "Overrides the SOAPAction for the request",
                "type": new QoreStringDataType(),
                "desc": "An optional string that will override the `SOAPAction` for the request; an empty string here "
                    "will prevent the `SOAPAction` from being sent",
            },
            "binding": <DataProviderOptionInfo>{
                "display_name": "SOAP Binding",
                "short_desc": "The SOAP binding name",
                "type": new QoreStringDataType(),
                "desc": "The SOAP binding name, if not provided the first binding assigned to the operation will be "
                    "used",
            },
        };
    }

    #! Returns the description of the record type, if any
    private:internal *hash<string, AbstractDataField> getRecordTypeIntern() {
        if (!op.output) {
            return;
        }
        AbstractDataProviderType type = op.output.getDataProviderType();
        if (type.getBaseTypeCode() == NT_LIST
            && (*hash<string, AbstractDataField> rv = type.getElementType().getFields())) {
            return rv;
        }
    }
}
}
