<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:t="urn:a" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:a"><w:message name="M"><w:part name="value" type="xs:string"/></w:message><w:portType name="P"><w:operation name="send"><w:input message="t:M"/><w:output message="t:M"/></w:operation></w:portType><w:binding name="B" type="t:P"><s:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/><w:operation name="send"><s:operation soapAction="send"/><w:input><s:body use="literal" namespace="urn:a"/></w:input><w:output><s:body use="literal" namespace="urn:a"/></w:output></w:operation></w:binding><w:service name="S"><w:port name="Endpoint" binding="t:B"><s:address location="http://example.invalid/soap"/></w:port></w:service></w:definitions>
