<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:root"><w:import namespace="urn:a" location="a.wsdl"/><w:import namespace="urn:b" location="b.wsdl"/></w:definitions>
