<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:t="urn:operation-ownership" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:s12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="urn:operation-ownership">
  <w:types><xs:schema targetNamespace="urn:operation-ownership" elementFormDefault="qualified">
    <xs:complexType name="Node"><xs:sequence>
      <xs:element name="count" type="xs:int"/>
      <xs:element name="next" type="t:Node" minOccurs="0"/>
      <xs:any namespace="##other" processContents="strict" minOccurs="0"/>
    </xs:sequence></xs:complexType>
    <xs:element name="request" type="t:Node"/>
    <xs:element name="reply" type="t:Node"/>
    <xs:element name="token" type="xs:string"/>
    <xs:element name="problem" type="xs:string"/>
  </xs:schema><xs:schema targetNamespace="urn:extension"><xs:element name="number" type="xs:int"/></xs:schema></w:types>
  <w:message name="Input"><w:part name="body" element="t:request"/></w:message>
  <w:message name="Output"><w:part name="body" element="t:reply"/></w:message>
  <w:message name="Auth"><w:part name="auth" element="t:token"/></w:message>
  <w:message name="Problem"><w:part name="detail" element="t:problem"/></w:message>
  <w:message name="Empty"/>
  <w:portType name="Port">
    <w:operation name="echo"><w:input message="t:Input"/><w:output message="t:Output"/>
      <w:fault name="Problem" message="t:Problem"/></w:operation>
    <w:operation name="notify"><w:input message="t:Auth"/></w:operation>
  </w:portType>
  <w:binding name="B11" type="t:Port"><s:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <w:operation name="echo"><s:operation soapAction="urn:echo"/>
      <w:input><s:body use="literal"/><s:header use="literal" message="t:Auth" part="auth"/></w:input>
      <w:output><s:body use="literal"/><s:header use="literal" message="t:Auth" part="auth"/></w:output>
      <w:fault name="Problem"><s:fault name="Problem" use="literal"/></w:fault>
    </w:operation>
    <w:operation name="notify"><s:operation soapAction="urn:notify"/><w:input><s:body use="literal"/></w:input></w:operation>
  </w:binding>
  <w:binding name="B12" type="t:Port"><s12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <w:operation name="echo"><s12:operation soapAction="urn:echo"/>
      <w:input><s12:body use="literal"/><s12:header use="literal" message="t:Auth" part="auth"/></w:input>
      <w:output><s12:body use="literal"/><s12:header use="literal" message="t:Auth" part="auth"/></w:output>
      <w:fault name="Problem"><s12:fault name="Problem" use="literal"/></w:fault>
    </w:operation>
    <w:operation name="notify"><s12:operation soapAction="urn:notify"/><w:input><s12:body use="literal"/></w:input></w:operation>
  </w:binding>
  <w:service name="Service">
    <w:port name="Port11" binding="t:B11"><s:address location="http://example.invalid/Service"/></w:port>
    <w:port name="Port12" binding="t:B12"><s12:address location="http://example.invalid/Service"/></w:port>
  </w:service>
</w:definitions>
