<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:empty-route" targetNamespace="urn:empty-route">
  <w:types>
    <xs:schema targetNamespace="urn:empty-route">
      <xs:element name="value" type="xs:string"/>
    </xs:schema>
  </w:types>
  <w:message name="Empty"/>
  <w:message name="Value">
    <w:part name="body" element="t:value"/>
  </w:message>
  <w:portType name="P">
    <w:operation name="first">
      <w:input message="t:Empty"/>
      <w:output message="t:Value"/>
    </w:operation>
    <w:operation name="second">
      <w:input message="t:Empty"/>
      <w:output message="t:Value"/>
    </w:operation>
    <w:operation name="scalar">
      <w:input message="t:Value"/>
      <w:output message="t:Value"/>
    </w:operation>
  </w:portType>
  <w:binding name="B" type="t:P">
    <s:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <w:operation name="first">
      <s:operation soapAction="urn:first"/>
      <w:input>
        <s:body use="literal"/>
      </w:input>
      <w:output>
        <s:body use="literal"/>
      </w:output>
    </w:operation>
    <w:operation name="second">
      <s:operation soapAction="urn:second"/>
      <w:input>
        <s:body use="literal"/>
      </w:input>
      <w:output>
        <s:body use="literal"/>
      </w:output>
    </w:operation>
    <w:operation name="scalar">
      <s:operation soapAction="urn:scalar"/>
      <w:input>
        <s:body use="literal"/>
      </w:input>
      <w:output>
        <s:body use="literal"/>
      </w:output>
    </w:operation>
  </w:binding>
  <w:service name="S">
    <w:port name="P" binding="t:B">
      <s:address location="http://example.invalid/"/>
    </w:port>
  </w:service>
</w:definitions>
