<?xml version="1.0"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:x="http://www.w3.org/2001/XMLSchema"
 xmlns:t="urn:header:a" targetNamespace="urn:header:a">
 <w:types><x:schema targetNamespace="urn:header:a">
  <x:element name="Token" type="x:int"/>
 </x:schema></w:types>
 <w:message name="H"><w:part name="token" element="t:Token"/></w:message>
</w:definitions>
