<?xml version="1.0"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:x="http://www.w3.org/2001/XMLSchema"
 xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:t="urn:header:root"
 xmlns:a="urn:header:a" xmlns:b="urn:header:b" targetNamespace="urn:header:root">
 <w:import namespace="urn:header:a" location="a.wsdl"/>
 <w:import namespace="urn:header:b" location="b.wsdl"/>
 <w:types><x:schema targetNamespace="urn:header:root">
  <x:element name="Body" type="x:int"/>
 </x:schema></w:types>
 <w:message name="M"><w:part name="body" element="t:Body"/></w:message>
 <w:portType name="P"><w:operation name="exchange"><w:input message="t:M"/><w:output message="t:M"/></w:operation></w:portType>
 <w:binding name="B" type="t:P"><s:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <w:operation name="exchange"><s:operation soapAction="urn:exchange"/>
   <w:input><s:body use="literal"/><s:header message="a:H" part="token" use="literal"/><s:header message="b:H" part="token" use="literal"/></w:input>
   <w:output><s:body use="literal"/><s:header message="a:H" part="token" use="literal"/><s:header message="b:H" part="token" use="literal"/></w:output>
  </w:operation>
 </w:binding>
 <w:service name="S"><w:port name="Endpoint" binding="t:B"><s:address location="http://example.invalid/soap"/></w:port></w:service>
</w:definitions>
