<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/"
 xmlns:h="http://schemas.xmlsoap.org/wsdl/http/" xmlns:m="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:x="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:request-url" targetNamespace="urn:request-url">
 <w:message name="Input"><w:part name="id" type="x:string"/></w:message>
 <w:message name="Output"><w:part name="result" type="x:string"/></w:message>
 <w:portType name="P"><w:operation name="send"><w:input message="t:Input"/><w:output message="t:Output"/></w:operation></w:portType>
 <w:binding name="B" type="t:P"><h:binding verb="GET"/>
  <w:operation name="send"><h:operation location="/send"/>
   <w:input><h:urlEncoded/></w:input><w:output><m:mimeXml part="result"/></w:output>
  </w:operation>
 </w:binding>
 <w:service name="S"><w:port name="Endpoint" binding="t:B"><h:address location="http://example.invalid/base/"/></w:port></w:service>
</w:definitions>
