<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/"
 xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:m="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="urn:attachments" targetNamespace="urn:attachments">
 <w:types><xs:schema targetNamespace="urn:attachments" elementFormDefault="qualified">
  <xs:element name="Text" type="xs:string"/>
  <xs:element name="Invoice"><xs:complexType><xs:sequence>
   <xs:element name="id" type="xs:int"/><xs:element name="label" type="xs:string"/>
  </xs:sequence></xs:complexType></xs:element>
 </xs:schema></w:types>
 <w:message name="Message"><w:part name="text" element="t:Text"/>
  <w:part name="data" type="xs:base64Binary"/><w:part name="invoice" element="t:Invoice"/>
 </w:message>
 <w:portType name="Port"><w:operation name="exchange">
  <w:input message="t:Message"/><w:output message="t:Message"/>
 </w:operation></w:portType>
 <w:binding name="Binding" type="t:Port">
  <s:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
  <w:operation name="exchange"><s:operation soapAction="urn:exchange"/>
   <w:input><m:multipartRelated>
    <m:part><m:content part="invoice" type="text/xml"/></m:part>
    <m:part><s:body use="literal" parts="text"/></m:part>
    <m:part><m:content part="data" type="application/octet-stream"/></m:part>
   </m:multipartRelated></w:input>
   <w:output><m:multipartRelated>
    <m:part><m:content part="data" type="application/octet-stream"/></m:part>
    <m:part><s:body use="literal" parts="text"/></m:part>
    <m:part><m:content part="invoice" type="text/xml"/></m:part>
   </m:multipartRelated></w:output>
  </w:operation>
 </w:binding>
 <w:service name="Service"><w:port name="Port" binding="t:Binding">
  <s:address location="http://127.0.0.1/service"/>
 </w:port></w:service>
</w:definitions>
