<?xml version="1.0" ?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:t="urn:ops" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:ops">
  <w:message name="M"/>
  <w:portType name="P">
    <w:operation name="oneway">
      <w:input message="t:M"/>
    </w:operation>
    <w:operation name="notification">
      <w:output message="t:M"/>
    </w:operation>
    <w:operation name="request-response">
      <w:input message="t:M"/>
      <w:output message="t:M"/>
    </w:operation>
    <w:operation name="solicit-response">
      <w:output message="t:M"/>
      <w:input message="t:M"/>
    </w:operation>
  </w:portType>
</w:definitions>
