<?xml version="1.0"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:t="urn:ops"
    xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:root">
  <w:import namespace="urn:ops" location="rr-input-only.wsdl"/>
  <w:portType name="P"/>
  <w:binding name="Imported" type="t:P">
    <s:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <w:operation name="lookup">
      <s:operation soapAction="lookup"/>
      <w:input name="ByName"><s:body use="literal" namespace="urn:ops"/></w:input>
      <w:output name="ResultName"><s:body use="literal" namespace="urn:ops"/></w:output>
    </w:operation>
  </w:binding>
</w:definitions>
