<?xml version="1.0" ?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:t="urn:ops" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:ops">
  <w:message name="M"/>
  <w:portType name="P">
    <w:operation name="lookup">
      <w:input name="ById" message="t:M"/>
      <w:output name="ResultId" message="t:M"/>
    </w:operation>
    <w:operation name="lookup">
      <w:input name="ByName" message="t:M"/>
      <w:output name="ResultName" message="t:M"/>
    </w:operation>
  </w:portType>
  <w:binding name="B" type="t:P">
    <s:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <w:operation name="lookup">
      <w:input>
        <s:body use="literal" namespace="urn:ops"/>
      </w:input>
      <w:output name="ResultName">
        <s:body use="literal" namespace="urn:ops"/>
      </w:output>
    </w:operation>
  </w:binding>
</w:definitions>
