<?xml version="1.0"?>
<!-- cda-types.xsd Copyright 2026 Qore Technologies, s.r.o. -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:cda="urn:hl7-org:v3"
    targetNamespace="urn:hl7-org:v3"
    elementFormDefault="qualified">

  <xsd:complexType name="ClinicalDocumentType">
    <xsd:sequence>
      <xsd:element name="templateId" type="cda:IdentifierType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="id" type="cda:IdentifierType"/>
      <xsd:element name="code" type="cda:CodeType"/>
      <xsd:element name="title" type="xsd:string"/>
      <xsd:element name="effectiveTime" type="cda:ValueType"/>
      <xsd:element name="confidentialityCode" type="cda:CodeType"/>
      <xsd:element name="languageCode" type="cda:CodeType"/>
      <xsd:element name="setId" type="cda:IdentifierType" minOccurs="0"/>
      <xsd:element name="versionNumber" type="cda:ValueType" minOccurs="0"/>
      <xsd:element name="recordTarget" type="cda:RecordTargetType" minOccurs="0"/>
      <xsd:element name="component" type="cda:DocumentComponentType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="IdentifierType">
    <xsd:attribute name="root" type="xsd:string" use="required"/>
    <xsd:attribute name="extension" type="xsd:string"/>
    <xsd:attribute name="assigningAuthorityName" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="CodeType">
    <xsd:attribute name="code" type="xsd:string"/>
    <xsd:attribute name="codeSystem" type="xsd:string"/>
    <xsd:attribute name="codeSystemName" type="xsd:string"/>
    <xsd:attribute name="displayName" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="ValueType">
    <xsd:attribute name="value" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="RecordTargetType">
    <xsd:sequence>
      <xsd:element name="patientRole" type="cda:PatientRoleType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="PatientRoleType">
    <xsd:sequence>
      <xsd:element name="id" type="cda:IdentifierType"/>
      <xsd:element name="patient" type="cda:PatientType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="PatientType">
    <xsd:sequence>
      <xsd:element name="name" type="cda:PersonNameType"/>
      <xsd:element name="administrativeGenderCode" type="cda:CodeType" minOccurs="0"/>
      <xsd:element name="birthTime" type="cda:ValueType" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="PersonNameType">
    <xsd:sequence>
      <xsd:element name="given" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="family" type="xsd:string" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="DocumentComponentType">
    <xsd:sequence>
      <xsd:element name="structuredBody" type="cda:StructuredBodyType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="StructuredBodyType">
    <xsd:sequence>
      <xsd:element name="component" type="cda:SectionComponentType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="SectionComponentType">
    <xsd:sequence>
      <xsd:element name="section" type="cda:SectionType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="SectionType">
    <xsd:sequence>
      <xsd:element name="code" type="cda:CodeType"/>
      <xsd:element name="title" type="xsd:string"/>
      <xsd:element name="text" type="cda:NarrativeTextType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="NarrativeTextType" mixed="true">
    <xsd:sequence>
      <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
