# Copyright (C) 2026 Qore Technologies, s.r.o.
# Apply after the name-edition fix; pinned archive bytes remain unchanged.

function(qore_xml_fix_libxml2_occurrence_flow source_dir binary_dir)
    get_target_property(_sources LibXml2 SOURCES)
    set(_input "")
    foreach(_entry IN LISTS _sources)
        get_filename_component(_name "${_entry}" NAME)
        if(_name STREQUAL "xmlschemas.c")
            if(_input)
                message(FATAL_ERROR "Duplicate libxml2 xmlschemas.c target source")
            endif()
            set(_input "${_entry}")
        endif()
    endforeach()
    if(NOT _input)
        message(FATAL_ERROR "Cannot locate libxml2 xmlschemas.c for occurrence data-flow fix")
    endif()
    if(IS_ABSOLUTE "${_input}")
        set(_path "${_input}")
    else()
        set(_path "${source_dir}/${_input}")
    endif()
    file(SHA256 "${_path}" _hash)
    set(_original_hash 0a948d8914296d9ca7a69fd55937f8950a12080f3ef22d4f3f5e6c493b351cfe)
    set(_fixed_hash c8a1eae8ea68df0bba7bad29e6aa5870346f2f117aaffddca5a0a0131c47bfe9)
    if(_hash STREQUAL _fixed_hash)
        return()
    endif()
    if(NOT _hash STREQUAL _original_hash)
        message(FATAL_ERROR "Unexpected libxml2 xmlschemas.c; cannot apply the occurrence data-flow fix")
    endif()
    file(READ "${_path}" _source)
    # Read the validated bounds from the particle that already owns them. This
    # makes the local/global declaration branches explicit to GCC's data-flow
    # analysis without dummy initialization or suppressing diagnostics.
    string(REPLACE [==[        particle->children = (xmlSchemaTreeItemPtr) decl;
        if ((min == 0) && (max == 0)) {]==] [==[        particle->children = (xmlSchemaTreeItemPtr) decl;
        if ((particle->minOccurs == 0) && (particle->maxOccurs == 0)) {]==] _source "${_source}")
    string(SHA256 _result_hash "${_source}")
    if(NOT _result_hash STREQUAL _fixed_hash)
        message(FATAL_ERROR "Pinned libxml2 occurrence fix did not match")
    endif()
    file(MAKE_DIRECTORY "${binary_dir}/qore-occurrence-flow-fix")
    set(_replacement "${binary_dir}/qore-occurrence-flow-fix/xmlschemas.c")
    file(WRITE "${_replacement}.tmp" "${_source}")
    configure_file("${_replacement}.tmp" "${_replacement}" COPYONLY)
    list(REMOVE_ITEM _sources "${_input}")
    list(APPEND _sources "${_replacement}")
    set_property(TARGET LibXml2 PROPERTY SOURCES "${_sources}")
    message(STATUS "XML module: applied libxml2 occurrence data-flow fix in the build tree")
endfunction()
