# Copyright (C) 2026 Qore Technologies, s.r.o.
# Validate explicit and implicit declarations after substitution resolution.
set(_qore_xml_element_consistency_dir "${CMAKE_CURRENT_LIST_DIR}")
function(qore_xml_fix_libxml2_element_consistency source_dir binary_dir)
    get_target_property(_sources LibXml2 SOURCES)
    set(_input "")
    foreach(_entry IN LISTS _sources)
        get_filename_component(_name "${_entry}" NAME)
        if(_name STREQUAL "xmlschemas.c")
            if(_input)
                message(FATAL_ERROR "Duplicate libxml2 xmlschemas.c target source")
            endif()
            set(_input "${_entry}")
        endif()
    endforeach()
    if(NOT _input)
        message(FATAL_ERROR "Cannot locate libxml2 xmlschemas.c for element declaration consistency")
    endif()
    if(IS_ABSOLUTE "${_input}")
        set(_path "${_input}")
    else()
        set(_path "${source_dir}/${_input}")
    endif()
    file(SHA256 "${_path}" _hash)
    if(_hash STREQUAL "a918602d87b2ed7a35f0d7d26189e9190365123966feb8525a9aba2344711d67")
        return()
    endif()
    if(NOT _hash STREQUAL "3c2709538ea99bd15fe64b61a30c96cfcab57153a074167bf23b89e32391674c")
        message(FATAL_ERROR "Unexpected libxml2 xmlschemas.c; cannot apply element declaration consistency")
    endif()
    file(READ "${_path}" _source)
    file(READ "${_qore_xml_element_consistency_dir}/libxml2-element-consistency.inc" _helper)
    string(REPLACE "static int\nxmlSchemaCheckParticleAttributions("
        "${_helper}\nstatic int\nxmlSchemaCheckParticleAttributions(" _source "${_source}")
    string(REPLACE [==[            result = xmlSchemaUpaVisit(&schema, root);
            if (result != 0) {]==] [==[            result = xmlSchemaUpaVisit(&schema, root);
            if (result == 0) {
                result = xmlSchemaCheckElementConsistency(parser, root);
            }
            if (result != 0) {]==] _source "${_source}")
    string(SHA256 _hash "${_source}")
    if(NOT _hash STREQUAL "a918602d87b2ed7a35f0d7d26189e9190365123966feb8525a9aba2344711d67")
        message(FATAL_ERROR "Pinned libxml2 element consistency fix did not match")
    endif()
    file(MAKE_DIRECTORY "${binary_dir}/qore-element-consistency-fix")
    set(_replacement "${binary_dir}/qore-element-consistency-fix/xmlschemas.c")
    file(WRITE "${_replacement}.tmp" "${_source}")
    configure_file("${_replacement}.tmp" "${_replacement}" COPYONLY)
    list(REMOVE_ITEM _sources "${_input}")
    list(APPEND _sources "${_replacement}")
    set_property(TARGET LibXml2 PROPERTY SOURCES "${_sources}")
    message(STATUS "XML module: applied libxml2 element declaration consistency in the build tree")
endfunction()
