# Copyright (C) 2026 Qore Technologies, s.r.o.
# Apply XSD 1.0 identity-table inheritance and local precedence.
set(_qore_xml_identity_tables_dir "${CMAKE_CURRENT_LIST_DIR}")
function(qore_xml_fix_libxml2_identity_tables source_dir binary_dir)
    get_target_property(_sources LibXml2 SOURCES)
    set(_input "")
    foreach(_entry IN LISTS _sources)
        get_filename_component(_name "${_entry}" NAME)
        if(_name STREQUAL "xmlschemas.c")
            if(_input)
                message(FATAL_ERROR "Duplicate libxml2 xmlschemas.c target source")
            endif()
            set(_input "${_entry}")
        endif()
    endforeach()
    if(NOT _input)
        message(FATAL_ERROR "Cannot locate libxml2 xmlschemas.c for identity table inheritance")
    endif()
    if(IS_ABSOLUTE "${_input}")
        set(_path "${_input}")
    else()
        set(_path "${source_dir}/${_input}")
    endif()
    file(SHA256 "${_path}" _hash)
    if(_hash STREQUAL "c41bfe71ac77dfc5b7ac5d363181d34e4d7a5f10026554860e19d0f9a143f8fd")
        return()
    endif()
    if(NOT _hash STREQUAL "d3ea6afbb2128b714b8d2156515062b351a11fdfec4ba3928ee531a0b6f873c8")
        message(FATAL_ERROR "Unexpected libxml2 xmlschemas.c; cannot apply identity table inheritance")
    endif()
    file(READ "${_path}" _source)
    set(_implementation "${_qore_xml_identity_tables_dir}/libxml2-identity-tables.inc")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_implementation}")
    file(READ "${_implementation}" _tables)
    string(FIND "${_source}" "static int\nxmlSchemaIDCFillNodeTables(" _start)
    string(FIND "${_source}" "/**\n * Check the cvc-idc-keyref constraints." _end)
    if(_start LESS 0 OR _end LESS _start)
        message(FATAL_ERROR "Cannot locate pinned libxml2 identity table implementation")
    endif()
    string(SUBSTRING "${_source}" 0 ${_start} _before)
    string(SUBSTRING "${_source}" ${_end} -1 _after)
    set(_source "${_before}${_tables}\n\n${_after}")
    string(REPLACE "xmlSchemaIDCAppendNodeTableItem(xmlSchemaPSVIIDCBindingPtr bind,"
        "xmlSchemaIDCAppendNodeTableItem(xmlSchemaValidCtxtPtr vctxt, xmlSchemaPSVIIDCBindingPtr bind,"
        _source "${_source}")
    string(FIND "${_source}" "xmlSchemaIDCAppendNodeTableItem(xmlSchemaValidCtxtPtr" _start)
    string(SUBSTRING "${_source}" ${_start} -1 _tail)
    string(FIND "${_tail}" "\n/**" _length)
    string(SUBSTRING "${_tail}" 0 ${_length} _append)
    string(REPLACE "xmlSchemaVErrMemory(NULL)" "xmlSchemaVErrMemory(vctxt)" _fixed_append "${_append}")
    string(REPLACE "${_append}" "${_fixed_append}" _source "${_source}")
    string(SHA256 _hash "${_source}")
    if(NOT _hash STREQUAL "c41bfe71ac77dfc5b7ac5d363181d34e4d7a5f10026554860e19d0f9a143f8fd")
        message(FATAL_ERROR "Pinned libxml2 identity table inheritance fix did not match")
    endif()
    file(MAKE_DIRECTORY "${binary_dir}/qore-identity-table-fix")
    set(_replacement "${binary_dir}/qore-identity-table-fix/xmlschemas.c")
    file(WRITE "${_replacement}.tmp" "${_source}")
    configure_file("${_replacement}.tmp" "${_replacement}" COPYONLY)
    list(REMOVE_ITEM _sources "${_input}")
    list(APPEND _sources "${_replacement}")
    set_property(TARGET LibXml2 PROPERTY SOURCES "${_sources}")
    message(STATUS "XML module: applied libxml2 identity table inheritance assessment in the build tree")
endfunction()
