<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" xmlns:t="urn:parts"
    xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:parts">
  <w:types><xs:schema targetNamespace="urn:parts">
    <xs:element name="Left" type="xs:int"/>
    <xs:element name="Right" type="xs:int"/>
    <xs:element name="Token" type="xs:int"/>
  </xs:schema></w:types>
  <w:message name="M">
    <w:part name="left" element="t:Left"/>
    <w:part name="right" element="t:Right"/>
  </w:message>
  <w:message name="H"><w:part name="token" element="t:Token"/></w:message>
  <w:portType name="P"><w:operation name="exchange">
    <w:input message="t:M"/><w:output message="t:M"/>
  </w:operation></w:portType>
  <w:binding name="B" type="t:P">
    <s:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <w:operation name="exchange"><s:operation soapAction="urn:exchange"/>
      <w:input><s:body use="literal" namespace="urn:wire" parts="left right"/></w:input>
      <w:output><s:body use="literal" namespace="urn:wire" parts="left right"/></w:output>
    </w:operation>
  </w:binding>
  <w:service name="S"><w:port name="Endpoint" binding="t:B">
    <s:address location="http://example.invalid/parts"/>
  </w:port></w:service>
</w:definitions>
