<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:bindings" xmlns:p="urn:ports" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/"><w:import namespace="urn:ports" location="port.wsdl"/><w:import namespace="urn:headers" location="headers.wsdl"/><w:binding name="B" type="p:P"><s:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/><w:operation name="send"><s:operation soapAction="send"/><w:input><s:body use="literal" namespace="urn:wire"/><s:header xmlns:h="urn:headers" message="h:H" part="token" use="literal"/></w:input><w:output><s:body use="literal" namespace="urn:wire"/></w:output></w:operation></w:binding></w:definitions>
