<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:headers" xmlns:xs="http://www.w3.org/2001/XMLSchema"><w:import namespace="urn:messages" location="messages.wsdl"/><w:message name="H"><w:part name="token" type="xs:string"/></w:message></w:definitions>
