<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:headers" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:h="urn:headers"><w:import namespace="urn:messages" location="messages.wsdl"/><w:types><xs:schema targetNamespace="urn:headers"><xs:element name="token" type="xs:string"/></xs:schema></w:types><w:message name="H"><w:part name="token" element="h:token"/></w:message></w:definitions>
