<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:messages" xmlns:xs="http://www.w3.org/2001/XMLSchema"><w:import namespace="urn:root" location="root.wsdl"/><w:message name="M"><w:part name="value" type="xs:string"/></w:message></w:definitions>
