<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:ports" ><w:import namespace="urn:messages" location="messages.wsdl"/><w:portType name="P"><w:operation name="send"><w:input xmlns:m="urn:messages" message="m:M"/><w:output xmlns="urn:messages" message="M"/><w:fault xmlns:m="urn:messages" name="Failure" message="m:M"/></w:operation></w:portType></w:definitions>
