<!-- Copyright (C) 2026 Qore Technologies, s.r.o. -->
<w:definitions xmlns:w="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:root" xmlns:b="urn:bindings" xmlns:s="http://schemas.xmlsoap.org/wsdl/soap/"><w:import namespace="urn:bindings" location="binding.wsdl"/><w:service name="S"><w:port name="Endpoint" binding="b:B"><s:address location="http://example.invalid/soap"/></w:port></w:service></w:definitions>
